name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

env:
  ENVIRONMENT: 'dev'
  BUILDKIT_PROGRESS: 'plain'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.23

      - name: Test
        run: |
          make test

      - name: Build binary
        run: |
          make build-binary

      # Lets us get branch name without bad characters like `/` that aren't allowed in the image tag.
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@955b5ba4560860f8a633bd24190941f16016e42c # v5.1.0

      - name: Set tag names
        if: github.ref_name == 'master'
        id: set_tag
        run: |
          echo "tag=${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        if: github.ref_name == 'master'
        # See doc at: https://github.com/grafana/shared-workflows/tree/main/actions/push-to-gar-docker
        uses: grafana/shared-workflows/actions/push-to-gar-docker@main
        with:
          platforms: linux/amd64,linux/arm64
          environment: ${{ env.ENVIRONMENT }}
          image_name: application-gateway-kubernetes-ingress
          context: .
          cache-to: type=inline
          push: true
          build-args: |
            REVISION=${{ env.GITHUB_SHA_SHORT }}
          tags: |-
            "${{ steps.set_tag.outputs.tag }}"

      - name: Set summary
        if: github.ref_name == 'master'
        run: |
          echo "**Docker Image:** ${{ steps.set_tag.outputs.tag }}" >> "$GITHUB_STEP_SUMMARY"
